import Head from 'next/head'
import Link from "next/link"
import Image from 'next/image'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'

export default function BlogHome({ posts }) {
  return (


    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      {posts.map((post, index) => (
        <Link href={`blog/${post.slug}`} key={index}>{post.frontMatter.title}</Link>
      ))}

    </div>
  )
}


export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'))

  const posts = files.map(filename => {
    const source = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const { data: frontMatter } = matter(source)

    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })

  return {
    props: {
      posts
    }
  }
}